import { Inter } from "next/font/google";
import "./globals.css";
import { Box, ChakraProvider, Stack } from "@chakra-ui/react";
import { Header } from "@/layout/Header";
import { MainLayout } from "@/layout/MainLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <MainLayout>
            {children}
          </MainLayout>
        </ChakraProvider>
      </body>
    </html>
  );
}
